-- AlterTable
ALTER TABLE "DoctorProfile" ALTER COLUMN "DNI" SET DEFAULT '99999999',
ALTER COLUMN "DNI" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "PatientProfile" ALTER COLUMN "DNI" SET DEFAULT '99999999',
ALTER COLUMN "DNI" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "phoneNumber" SET DATA TYPE TEXT;
